spring:
  application:
    name: auth-service

  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://host.docker.internal:5432/auth_db}
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10        # Max connections per service
      minimum-idle: 5              # Idle connections
      idle-timeout: 30000          # 30 seconds
      max-lifetime: 1800000        # 30 minutes
      connection-timeout: 30000    # 30 seconds
      pool-name: ${spring.application.name}-pool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 6000
      connect-timeout: 6000
  cache:
    type: redis

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

  elasticsearch:
    uris: ${ELASTIC_URI:http://elasticsearch:9200}

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/eureka/

server:
  port: ${SERVER_PORT:8087}

  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:supersecretkeythatshouldbereplacedandstoredsecurely}
  access-expiration: 3600          # seconds (1h)
  refresh-expiration: 86400        # seconds (24h)

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.cache.interceptor: DEBUG


elastic:
  host:
    name: elasticsearch

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: auth-service

app:
  seed-auth: true

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8086/api/v1/user}

category:
  service:
    url: ${CATEGORY_SERVICE_URL:http://category-service:8082/api/v1/category}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8081/api/v1/product}

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://inventory-service:8083/api/v1/inventory}
