spring:
  application:
    name: inventory-service

  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/inventory_db}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:inventory-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection:

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000
      connect-timeout: 6000
  cache:
    type: redis

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${SERVER_PORT:8091}

  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:supersecretkeythatshouldbereplacedandstoredsecurely}

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.cache.interceptor: DEBUG


elastic:
  host:
    name: elasticsearch

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: inventory-service
app:
  seed-inventory: true

category:
  service:
    url: ${CATEGORY_SERVICE_URL:http://localhost:8082/api/v1/category}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081/api/v1/project}
