spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8761}

  servlet:
    context-path: /eureka

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false
    home-page-url: http://localhost:8761/eureka/
    status-page-url: http://localhost:8761/eureka/actuator/info
    health-check-url: http://localhost:8761/eureka/actuator/health
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.cache.interceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: eureka-server