global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8080']

  - job_name: 'category-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'category-service:8090' ]

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'inventory-service:8091' ]

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:8092' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:8094' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'auth-service:8095' ]
